
name: Generate Snake

on:
  # Executa todo dia Ã  meia-noite UTC
  schedule:
    - cron: "0 0 * * *"
  # Permite rodar manualmente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Gerar SVG do snake
        uses: Platane/snk@v3
        with:
          github_user_name: RafaelDawkins
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Publicar no branch 'output'
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
